// <auto-generated />
using System;
using GymStation.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GymStation.Infrastructure.Migrations
{
    [DbContext(typeof(GymStationDbContext))]
    [Migration("20260802034321_AddLedgerManagement")]
    partial class AddLedgerManagement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClassSessionClassTypes", b =>
                {
                    b.Property<Guid>("ClassSessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassTypesId")
                        .HasColumnType("uuid");

                    b.HasKey("ClassSessionId", "ClassTypesId");

                    b.HasIndex("ClassTypesId");

                    b.ToTable("ClassSessionClassTypes");
                });

            modelBuilder.Entity("ClassTemplateClassTypes", b =>
                {
                    b.Property<Guid>("ClassTemplateId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassTypesId")
                        .HasColumnType("uuid");

                    b.HasKey("ClassTemplateId", "ClassTypesId");

                    b.HasIndex("ClassTypesId");

                    b.ToTable("ClassTemplateClassTypes");
                });

            modelBuilder.Entity("GymStation.Domain.Attendance.AttendanceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CheckedInUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ConfirmedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GymId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("SessionId", "PersonId")
                        .IsUnique();

                    b.HasIndex("GymId", "PersonId", "Status");

                    b.ToTable("AttendanceRecords");
                });

            modelBuilder.Entity("GymStation.Domain.Events.EventRsvp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GymId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EventId", "PersonId")
                        .IsUnique();

                    b.ToTable("EventRsvps");
                });

            modelBuilder.Entity("GymStation.Domain.Events.GymEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Details")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("GymId")
                        .HasColumnType("uuid");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("PublishedByPersonId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("StartsOn")
                        .HasColumnType("date");

                    b.Property<string>("TimeInfo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("GymId", "StartsOn");

                    b.ToTable("GymEvents");
                });

            modelBuilder.Entity("GymStation.Domain.Money.Charge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("CycleKey")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("GymId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("RaisedOn")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("GymId", "PersonId", "CycleKey")
                        .IsUnique()
                        .HasFilter("\"CycleKey\" IS NOT NULL");

                    b.ToTable("Charges");
                });

            modelBuilder.Entity("GymStation.Domain.Money.Expense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GymId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid?>("RecurringExpenseId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("SpentOn")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("GymId", "SpentOn");

                    b.HasIndex("RecurringExpenseId", "SpentOn")
                        .IsUnique()
                        .HasFilter("\"RecurringExpenseId\" IS NOT NULL");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("GymStation.Domain.Money.ExpenseCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Archived")
                        .HasColumnType("boolean");

                    b.Property<Guid>("GymId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Id");

                    b.HasIndex("GymId", "Name")
                        .IsUnique();

                    b.ToTable("ExpenseCategories");
                });

            modelBuilder.Entity("GymStation.Domain.Money.MembershipPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Archived")
                        .HasColumnType("boolean");

                    b.Property<int>("Cadence")
                        .HasColumnType("integer");

                    b.Property<Guid>("GymId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("GymId", "Name")
                        .IsUnique();

                    b.ToTable("MembershipPlans");
                });

            modelBuilder.Entity("GymStation.Domain.Money.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid>("GymId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("ReceivedOn")
                        .HasColumnType("date");

                    b.Property<Guid?>("RecordedByPersonId")
                        .HasColumnType("uuid");

                    b.Property<string>("VoidReason")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid?>("VoidedByPersonId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("VoidedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("GymStation.Domain.Money.RecurringExpense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<int>("DayOfMonth")
                        .HasColumnType("integer");

                    b.Property<Guid>("GymId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("RecurringExpenses");
                });

            modelBuilder.Entity("GymStation.Domain.Notifications.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GymId")
                        .HasColumnType("uuid");

                    b.Property<string>("LinkPath")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("ReadUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RecipientUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("RecipientUserId", "ReadUtc");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("GymStation.Domain.Notifications.NotificationDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AttemptedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Channel")
                        .HasColumnType("integer");

                    b.Property<string>("Error")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("GymId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NotificationId");

                    b.HasIndex("Status", "Channel");

                    b.ToTable("NotificationDeliveries");
                });

            modelBuilder.Entity("GymStation.Domain.People.GuardianLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChildPersonId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GuardianUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GymId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChildPersonId");

                    b.HasIndex("GuardianUserId", "ChildPersonId")
                        .IsUnique();

                    b.ToTable("GuardianLinks");
                });

            modelBuilder.Entity("GymStation.Domain.People.InstructorProfile", b =>
                {
                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<string>("Bio")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ExperienceSummary")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("GymId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("PayRate")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("PayRateUnit")
                        .HasColumnType("integer");

                    b.HasKey("PersonId");

                    b.ToTable("InstructorProfiles");
                });

            modelBuilder.Entity("GymStation.Domain.People.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Archived")
                        .HasColumnType("boolean");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("GymId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("JoinedOn")
                        .HasColumnType("date");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid?>("MembershipPlanId")
                        .HasColumnType("uuid");

                    b.Property<string>("PortraitPath")
                        .HasColumnType("text");

                    b.Property<int>("Roles")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GymId", "UserId")
                        .IsUnique()
                        .HasFilter("\"UserId\" IS NOT NULL");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("GymStation.Domain.Ranks.Rank", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BandColorHex")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<string>("BarColorHex")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<int>("MaxStripes")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("RankSystemId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RankSystemId", "Order")
                        .IsUnique();

                    b.ToTable("Ranks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111201"),
                            BandColorHex = "#E9E6DC",
                            BarColorHex = "#17181A",
                            MaxStripes = 4,
                            Name = "White",
                            Order = 1,
                            RankSystemId = new Guid("11111111-1111-1111-1111-111111111101")
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111202"),
                            BandColorHex = "#2456A6",
                            BarColorHex = "#17181A",
                            MaxStripes = 4,
                            Name = "Blue",
                            Order = 2,
                            RankSystemId = new Guid("11111111-1111-1111-1111-111111111101")
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111203"),
                            BandColorHex = "#5C3D93",
                            BarColorHex = "#17181A",
                            MaxStripes = 4,
                            Name = "Purple",
                            Order = 3,
                            RankSystemId = new Guid("11111111-1111-1111-1111-111111111101")
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111204"),
                            BandColorHex = "#7A5230",
                            BarColorHex = "#17181A",
                            MaxStripes = 4,
                            Name = "Brown",
                            Order = 4,
                            RankSystemId = new Guid("11111111-1111-1111-1111-111111111101")
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111205"),
                            BandColorHex = "#17181A",
                            BarColorHex = "#A31D26",
                            MaxStripes = 6,
                            Name = "Black",
                            Order = 5,
                            RankSystemId = new Guid("11111111-1111-1111-1111-111111111101")
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111206"),
                            BandColorHex = "#521A1E",
                            BarColorHex = "#17181A",
                            MaxStripes = 0,
                            Name = "Red & Black",
                            Order = 6,
                            RankSystemId = new Guid("11111111-1111-1111-1111-111111111101")
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111207"),
                            BandColorHex = "#A31D26",
                            BarColorHex = "#E9E6DC",
                            MaxStripes = 0,
                            Name = "Red & White",
                            Order = 7,
                            RankSystemId = new Guid("11111111-1111-1111-1111-111111111101")
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111208"),
                            BandColorHex = "#A31D26",
                            BarColorHex = "#7A1218",
                            MaxStripes = 0,
                            Name = "Red",
                            Order = 8,
                            RankSystemId = new Guid("11111111-1111-1111-1111-111111111101")
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111300"),
                            BandColorHex = "#E9E6DC",
                            BarColorHex = "#17181A",
                            MaxStripes = 4,
                            Name = "White",
                            Order = 0,
                            RankSystemId = new Guid("11111111-1111-1111-1111-111111111102")
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111301"),
                            BandColorHex = "#B8BDC6",
                            BarColorHex = "#17181A",
                            MaxStripes = 4,
                            Name = "Grey-White",
                            Order = 1,
                            RankSystemId = new Guid("11111111-1111-1111-1111-111111111102")
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111302"),
                            BandColorHex = "#9BA1AB",
                            BarColorHex = "#17181A",
                            MaxStripes = 4,
                            Name = "Grey",
                            Order = 2,
                            RankSystemId = new Guid("11111111-1111-1111-1111-111111111102")
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111303"),
                            BandColorHex = "#7E848E",
                            BarColorHex = "#17181A",
                            MaxStripes = 4,
                            Name = "Grey-Black",
                            Order = 3,
                            RankSystemId = new Guid("11111111-1111-1111-1111-111111111102")
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111304"),
                            BandColorHex = "#F0D275",
                            BarColorHex = "#17181A",
                            MaxStripes = 4,
                            Name = "Yellow-White",
                            Order = 4,
                            RankSystemId = new Guid("11111111-1111-1111-1111-111111111102")
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111305"),
                            BandColorHex = "#E8C13A",
                            BarColorHex = "#17181A",
                            MaxStripes = 4,
                            Name = "Yellow",
                            Order = 5,
                            RankSystemId = new Guid("11111111-1111-1111-1111-111111111102")
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111306"),
                            BandColorHex = "#C7A32E",
                            BarColorHex = "#17181A",
                            MaxStripes = 4,
                            Name = "Yellow-Black",
                            Order = 6,
                            RankSystemId = new Guid("11111111-1111-1111-1111-111111111102")
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111307"),
                            BandColorHex = "#EBA06A",
                            BarColorHex = "#17181A",
                            MaxStripes = 4,
                            Name = "Orange-White",
                            Order = 7,
                            RankSystemId = new Guid("11111111-1111-1111-1111-111111111102")
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111308"),
                            BandColorHex = "#E07B39",
                            BarColorHex = "#17181A",
                            MaxStripes = 4,
                            Name = "Orange",
                            Order = 8,
                            RankSystemId = new Guid("11111111-1111-1111-1111-111111111102")
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111309"),
                            BandColorHex = "#BF6830",
                            BarColorHex = "#17181A",
                            MaxStripes = 4,
                            Name = "Orange-Black",
                            Order = 9,
                            RankSystemId = new Guid("11111111-1111-1111-1111-111111111102")
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111310"),
                            BandColorHex = "#74B18C",
                            BarColorHex = "#17181A",
                            MaxStripes = 4,
                            Name = "Green-White",
                            Order = 10,
                            RankSystemId = new Guid("11111111-1111-1111-1111-111111111102")
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111311"),
                            BandColorHex = "#3E8E5A",
                            BarColorHex = "#17181A",
                            MaxStripes = 4,
                            Name = "Green",
                            Order = 11,
                            RankSystemId = new Guid("11111111-1111-1111-1111-111111111102")
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111312"),
                            BandColorHex = "#33774B",
                            BarColorHex = "#17181A",
                            MaxStripes = 4,
                            Name = "Green-Black",
                            Order = 12,
                            RankSystemId = new Guid("11111111-1111-1111-1111-111111111102")
                        });
                });

            modelBuilder.Entity("GymStation.Domain.Ranks.RankAward", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AwardedByPersonId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("AwardedOn")
                        .HasColumnType("date");

                    b.Property<Guid>("GymId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RankId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("RecordedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("SelfReported")
                        .HasColumnType("boolean");

                    b.Property<int>("Stripes")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("RankId");

                    b.HasIndex("GymId", "PersonId", "AwardedOn");

                    b.ToTable("RankAwards");
                });

            modelBuilder.Entity("GymStation.Domain.Ranks.RankSystem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("GymId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsSeeded")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.ToTable("RankSystems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111101"),
                            IsSeeded = true,
                            Name = "IBJJF Adult"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111102"),
                            IsSeeded = true,
                            Name = "IBJJF Kids"
                        });
                });

            modelBuilder.Entity("GymStation.Domain.Scheduling.ClassSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CancelledReason")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid>("GymId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InstructorPersonId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GymId", "Date");

                    b.HasIndex("GymId", "TemplateId", "Date")
                        .IsUnique()
                        .HasFilter("\"TemplateId\" IS NOT NULL");

                    b.ToTable("ClassSessions");
                });

            modelBuilder.Entity("GymStation.Domain.Scheduling.ClassTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<int>("Day")
                        .HasColumnType("integer");

                    b.Property<Guid?>("DefaultInstructorPersonId")
                        .HasColumnType("uuid");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid>("GymId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.ToTable("ClassTemplates");
                });

            modelBuilder.Entity("GymStation.Domain.Scheduling.ClassType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Archived")
                        .HasColumnType("boolean");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<Guid>("GymId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("GymId", "Name")
                        .IsUnique();

                    b.ToTable("ClassTypes");
                });

            modelBuilder.Entity("GymStation.Domain.Scheduling.SubstitutionRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AcceptedByPersonId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AcceptedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EscalatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GymId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid?>("ProposedSubPersonId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequestedByPersonId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("RequestedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ResolvedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("GymId", "Status");

                    b.ToTable("SubstitutionRequests");
                });

            modelBuilder.Entity("GymStation.Domain.Tenancy.Gym", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Gyms");
                });

            modelBuilder.Entity("GymStation.Domain.Tenancy.GymSettings", b =>
                {
                    b.Property<Guid>("GymId")
                        .HasColumnType("uuid");

                    b.Property<string>("AccentColorHex")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<int>("CheckInWindowMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("DefaultThemeDark")
                        .HasColumnType("boolean");

                    b.Property<string>("HeroPath")
                        .HasColumnType("text");

                    b.Property<string>("LogoPath")
                        .HasColumnType("text");

                    b.Property<bool>("OpenClaimsEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("SubstitutionMode")
                        .HasColumnType("integer");

                    b.HasKey("GymId");

                    b.ToTable("GymSettings");
                });

            modelBuilder.Entity("GymStation.Domain.Training.TrainingEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("EntryDate")
                        .HasColumnType("date");

                    b.Property<Guid>("GymId")
                        .HasColumnType("uuid");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<int?>("SelfReportedMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GymId", "PersonId", "EntryDate");

                    b.ToTable("TrainingEntries");
                });

            modelBuilder.Entity("GymStation.Domain.Training.TrainingRoll", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GymId")
                        .HasColumnType("uuid");

                    b.Property<string>("PartnerLabel")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid?>("PartnerPersonId")
                        .HasColumnType("uuid");

                    b.Property<string>("Summary")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("TrainingEntryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TrainingEntryId");

                    b.ToTable("TrainingRolls");
                });

            modelBuilder.Entity("GymStation.Infrastructure.Identity.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool?>("PreferredThemeDark")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ClassSessionClassTypes", b =>
                {
                    b.HasOne("GymStation.Domain.Scheduling.ClassSession", null)
                        .WithMany()
                        .HasForeignKey("ClassSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymStation.Domain.Scheduling.ClassType", null)
                        .WithMany()
                        .HasForeignKey("ClassTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClassTemplateClassTypes", b =>
                {
                    b.HasOne("GymStation.Domain.Scheduling.ClassTemplate", null)
                        .WithMany()
                        .HasForeignKey("ClassTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymStation.Domain.Scheduling.ClassType", null)
                        .WithMany()
                        .HasForeignKey("ClassTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GymStation.Domain.Attendance.AttendanceRecord", b =>
                {
                    b.HasOne("GymStation.Domain.People.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymStation.Domain.Scheduling.ClassSession", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("GymStation.Domain.Events.EventRsvp", b =>
                {
                    b.HasOne("GymStation.Domain.Events.GymEvent", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GymStation.Domain.Money.Charge", b =>
                {
                    b.HasOne("GymStation.Domain.People.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("GymStation.Domain.Money.Expense", b =>
                {
                    b.HasOne("GymStation.Domain.Money.ExpenseCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("GymStation.Domain.Money.Payment", b =>
                {
                    b.HasOne("GymStation.Domain.People.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("GymStation.Domain.Money.RecurringExpense", b =>
                {
                    b.HasOne("GymStation.Domain.Money.ExpenseCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("GymStation.Domain.Notifications.NotificationDelivery", b =>
                {
                    b.HasOne("GymStation.Domain.Notifications.Notification", null)
                        .WithMany("Deliveries")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GymStation.Domain.People.GuardianLink", b =>
                {
                    b.HasOne("GymStation.Domain.People.Person", "ChildPerson")
                        .WithMany()
                        .HasForeignKey("ChildPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChildPerson");
                });

            modelBuilder.Entity("GymStation.Domain.People.InstructorProfile", b =>
                {
                    b.HasOne("GymStation.Domain.People.Person", "Person")
                        .WithOne()
                        .HasForeignKey("GymStation.Domain.People.InstructorProfile", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("GymStation.Domain.Ranks.Rank", b =>
                {
                    b.HasOne("GymStation.Domain.Ranks.RankSystem", null)
                        .WithMany("Ranks")
                        .HasForeignKey("RankSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GymStation.Domain.Ranks.RankAward", b =>
                {
                    b.HasOne("GymStation.Domain.People.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymStation.Domain.Ranks.Rank", "Rank")
                        .WithMany()
                        .HasForeignKey("RankId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Rank");
                });

            modelBuilder.Entity("GymStation.Domain.Scheduling.SubstitutionRequest", b =>
                {
                    b.HasOne("GymStation.Domain.Scheduling.ClassSession", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("GymStation.Domain.Tenancy.GymSettings", b =>
                {
                    b.HasOne("GymStation.Domain.Tenancy.Gym", null)
                        .WithOne("Settings")
                        .HasForeignKey("GymStation.Domain.Tenancy.GymSettings", "GymId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GymStation.Domain.Training.TrainingRoll", b =>
                {
                    b.HasOne("GymStation.Domain.Training.TrainingEntry", null)
                        .WithMany("Rolls")
                        .HasForeignKey("TrainingEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("GymStation.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("GymStation.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymStation.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("GymStation.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GymStation.Domain.Notifications.Notification", b =>
                {
                    b.Navigation("Deliveries");
                });

            modelBuilder.Entity("GymStation.Domain.Ranks.RankSystem", b =>
                {
                    b.Navigation("Ranks");
                });

            modelBuilder.Entity("GymStation.Domain.Tenancy.Gym", b =>
                {
                    b.Navigation("Settings")
                        .IsRequired();
                });

            modelBuilder.Entity("GymStation.Domain.Training.TrainingEntry", b =>
                {
                    b.Navigation("Rolls");
                });
#pragma warning restore 612, 618
        }
    }
}
