// <auto-generated />
using System;
using GymStation.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GymStation.Infrastructure.Migrations
{
    [DbContext(typeof(GymStationDbContext))]
    [Migration("20260731232355_AddPeopleAndRanks")]
    partial class AddPeopleAndRanks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GymStation.Domain.People.GuardianLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChildPersonId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GuardianUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GymId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChildPersonId");

                    b.HasIndex("GuardianUserId", "ChildPersonId")
                        .IsUnique();

                    b.ToTable("GuardianLinks");
                });

            modelBuilder.Entity("GymStation.Domain.People.InstructorProfile", b =>
                {
                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<string>("Bio")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ExperienceSummary")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("GymId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("PayRate")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("PayRateUnit")
                        .HasColumnType("integer");

                    b.HasKey("PersonId");

                    b.ToTable("InstructorProfiles");
                });

            modelBuilder.Entity("GymStation.Domain.People.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Archived")
                        .HasColumnType("boolean");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("GymId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("JoinedOn")
                        .HasColumnType("date");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("PortraitPath")
                        .HasColumnType("text");

                    b.Property<int>("Roles")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GymId", "UserId")
                        .IsUnique()
                        .HasFilter("\"UserId\" IS NOT NULL");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("GymStation.Domain.Ranks.Rank", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BandColorHex")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<string>("BarColorHex")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<int>("MaxStripes")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("RankSystemId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RankSystemId", "Order")
                        .IsUnique();

                    b.ToTable("Ranks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111201"),
                            BandColorHex = "#E9E6DC",
                            BarColorHex = "#17181A",
                            MaxStripes = 4,
                            Name = "White",
                            Order = 1,
                            RankSystemId = new Guid("11111111-1111-1111-1111-111111111101")
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111202"),
                            BandColorHex = "#2456A6",
                            BarColorHex = "#17181A",
                            MaxStripes = 4,
                            Name = "Blue",
                            Order = 2,
                            RankSystemId = new Guid("11111111-1111-1111-1111-111111111101")
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111203"),
                            BandColorHex = "#5C3D93",
                            BarColorHex = "#17181A",
                            MaxStripes = 4,
                            Name = "Purple",
                            Order = 3,
                            RankSystemId = new Guid("11111111-1111-1111-1111-111111111101")
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111204"),
                            BandColorHex = "#7A5230",
                            BarColorHex = "#17181A",
                            MaxStripes = 4,
                            Name = "Brown",
                            Order = 4,
                            RankSystemId = new Guid("11111111-1111-1111-1111-111111111101")
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111205"),
                            BandColorHex = "#17181A",
                            BarColorHex = "#A31D26",
                            MaxStripes = 6,
                            Name = "Black",
                            Order = 5,
                            RankSystemId = new Guid("11111111-1111-1111-1111-111111111101")
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111301"),
                            BandColorHex = "#B8BDC6",
                            BarColorHex = "#17181A",
                            MaxStripes = 4,
                            Name = "Grey-White",
                            Order = 1,
                            RankSystemId = new Guid("11111111-1111-1111-1111-111111111102")
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111302"),
                            BandColorHex = "#9BA1AB",
                            BarColorHex = "#17181A",
                            MaxStripes = 4,
                            Name = "Grey",
                            Order = 2,
                            RankSystemId = new Guid("11111111-1111-1111-1111-111111111102")
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111303"),
                            BandColorHex = "#7E848E",
                            BarColorHex = "#17181A",
                            MaxStripes = 4,
                            Name = "Grey-Black",
                            Order = 3,
                            RankSystemId = new Guid("11111111-1111-1111-1111-111111111102")
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111304"),
                            BandColorHex = "#F0D275",
                            BarColorHex = "#17181A",
                            MaxStripes = 4,
                            Name = "Yellow-White",
                            Order = 4,
                            RankSystemId = new Guid("11111111-1111-1111-1111-111111111102")
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111305"),
                            BandColorHex = "#E8C13A",
                            BarColorHex = "#17181A",
                            MaxStripes = 4,
                            Name = "Yellow",
                            Order = 5,
                            RankSystemId = new Guid("11111111-1111-1111-1111-111111111102")
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111306"),
                            BandColorHex = "#C7A32E",
                            BarColorHex = "#17181A",
                            MaxStripes = 4,
                            Name = "Yellow-Black",
                            Order = 6,
                            RankSystemId = new Guid("11111111-1111-1111-1111-111111111102")
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111307"),
                            BandColorHex = "#EBA06A",
                            BarColorHex = "#17181A",
                            MaxStripes = 4,
                            Name = "Orange-White",
                            Order = 7,
                            RankSystemId = new Guid("11111111-1111-1111-1111-111111111102")
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111308"),
                            BandColorHex = "#E07B39",
                            BarColorHex = "#17181A",
                            MaxStripes = 4,
                            Name = "Orange",
                            Order = 8,
                            RankSystemId = new Guid("11111111-1111-1111-1111-111111111102")
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111309"),
                            BandColorHex = "#BF6830",
                            BarColorHex = "#17181A",
                            MaxStripes = 4,
                            Name = "Orange-Black",
                            Order = 9,
                            RankSystemId = new Guid("11111111-1111-1111-1111-111111111102")
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111310"),
                            BandColorHex = "#74B18C",
                            BarColorHex = "#17181A",
                            MaxStripes = 4,
                            Name = "Green-White",
                            Order = 10,
                            RankSystemId = new Guid("11111111-1111-1111-1111-111111111102")
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111311"),
                            BandColorHex = "#3E8E5A",
                            BarColorHex = "#17181A",
                            MaxStripes = 4,
                            Name = "Green",
                            Order = 11,
                            RankSystemId = new Guid("11111111-1111-1111-1111-111111111102")
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111312"),
                            BandColorHex = "#33774B",
                            BarColorHex = "#17181A",
                            MaxStripes = 4,
                            Name = "Green-Black",
                            Order = 12,
                            RankSystemId = new Guid("11111111-1111-1111-1111-111111111102")
                        });
                });

            modelBuilder.Entity("GymStation.Domain.Ranks.RankAward", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AwardedByPersonId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("AwardedOn")
                        .HasColumnType("date");

                    b.Property<Guid>("GymId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RankId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("RecordedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("SelfReported")
                        .HasColumnType("boolean");

                    b.Property<int>("Stripes")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("RankId");

                    b.HasIndex("GymId", "PersonId", "AwardedOn");

                    b.ToTable("RankAwards");
                });

            modelBuilder.Entity("GymStation.Domain.Ranks.RankSystem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("GymId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsSeeded")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.ToTable("RankSystems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111101"),
                            IsSeeded = true,
                            Name = "IBJJF Adult"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111102"),
                            IsSeeded = true,
                            Name = "IBJJF Kids"
                        });
                });

            modelBuilder.Entity("GymStation.Domain.Tenancy.Gym", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Gyms");
                });

            modelBuilder.Entity("GymStation.Domain.Tenancy.GymSettings", b =>
                {
                    b.Property<Guid>("GymId")
                        .HasColumnType("uuid");

                    b.Property<string>("AccentColorHex")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<int>("CheckInWindowMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("DefaultThemeDark")
                        .HasColumnType("boolean");

                    b.Property<bool>("OpenClaimsEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("SubstitutionMode")
                        .HasColumnType("integer");

                    b.HasKey("GymId");

                    b.ToTable("GymSettings");
                });

            modelBuilder.Entity("GymStation.Infrastructure.Identity.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GymStation.Domain.People.GuardianLink", b =>
                {
                    b.HasOne("GymStation.Domain.People.Person", "ChildPerson")
                        .WithMany()
                        .HasForeignKey("ChildPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChildPerson");
                });

            modelBuilder.Entity("GymStation.Domain.People.InstructorProfile", b =>
                {
                    b.HasOne("GymStation.Domain.People.Person", "Person")
                        .WithOne()
                        .HasForeignKey("GymStation.Domain.People.InstructorProfile", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("GymStation.Domain.Ranks.Rank", b =>
                {
                    b.HasOne("GymStation.Domain.Ranks.RankSystem", null)
                        .WithMany("Ranks")
                        .HasForeignKey("RankSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GymStation.Domain.Ranks.RankAward", b =>
                {
                    b.HasOne("GymStation.Domain.People.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymStation.Domain.Ranks.Rank", "Rank")
                        .WithMany()
                        .HasForeignKey("RankId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Rank");
                });

            modelBuilder.Entity("GymStation.Domain.Tenancy.GymSettings", b =>
                {
                    b.HasOne("GymStation.Domain.Tenancy.Gym", null)
                        .WithOne("Settings")
                        .HasForeignKey("GymStation.Domain.Tenancy.GymSettings", "GymId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("GymStation.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("GymStation.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymStation.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("GymStation.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GymStation.Domain.Ranks.RankSystem", b =>
                {
                    b.Navigation("Ranks");
                });

            modelBuilder.Entity("GymStation.Domain.Tenancy.Gym", b =>
                {
                    b.Navigation("Settings")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
